shield_enable: false
credential_provider: shield
credentials:
  shield:
    user: ''
    pass: ''
print: 'Hello! :)'
debug_header: false
allowlist: ''
domains: ''
method: 0
paths: ''
http_method_allowlist: {  }
allow_cli: true
unset_basic_auth_headers: true
_core:
  default_config_hash: FLJZME3II5fjmMSrdEvJHp95ZJf8V_X0jbX0VdVU1BU
langcode: es
