country:
  default: PE
first_day: 0
timezone:
  default: America/Lima
  user:
    warn: true
    default: 1
    configurable: true
_core:
  default_config_hash: V9UurX2GPT05NWKG9f2GWQqFG2TRG8vczidwjpy7Woo
langcode: es
